/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminTestimonialsIndexRouteImport } from './routes/admin.testimonials.index'
import { Route as AdminServicesIndexRouteImport } from './routes/admin.services.index'
import { Route as AdminPopupIndexRouteImport } from './routes/admin.popup.index'
import { Route as AdminHomepageIndexRouteImport } from './routes/admin.homepage.index'
import { Route as AdminGalleryIndexRouteImport } from './routes/admin.gallery.index'
import { Route as AdminFaqsIndexRouteImport } from './routes/admin.faqs.index'
import { Route as AdminDoctorsIndexRouteImport } from './routes/admin.doctors.index'
import { Route as AdminCareersIndexRouteImport } from './routes/admin.careers.index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin.blog.index'
import { Route as AdminAppointmentsIndexRouteImport } from './routes/admin.appointments.index'
import { Route as AdminBlogIdRouteImport } from './routes/admin.blog.$id'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimonialsIndexRoute = AdminTestimonialsIndexRouteImport.update({
  id: '/admin/testimonials/',
  path: '/admin/testimonials/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesIndexRoute = AdminServicesIndexRouteImport.update({
  id: '/admin/services/',
  path: '/admin/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPopupIndexRoute = AdminPopupIndexRouteImport.update({
  id: '/admin/popup/',
  path: '/admin/popup/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHomepageIndexRoute = AdminHomepageIndexRouteImport.update({
  id: '/admin/homepage/',
  path: '/admin/homepage/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGalleryIndexRoute = AdminGalleryIndexRouteImport.update({
  id: '/admin/gallery/',
  path: '/admin/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFaqsIndexRoute = AdminFaqsIndexRouteImport.update({
  id: '/admin/faqs/',
  path: '/admin/faqs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDoctorsIndexRoute = AdminDoctorsIndexRouteImport.update({
  id: '/admin/doctors/',
  path: '/admin/doctors/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCareersIndexRoute = AdminCareersIndexRouteImport.update({
  id: '/admin/careers/',
  path: '/admin/careers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/admin/blog/',
  path: '/admin/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppointmentsIndexRoute = AdminAppointmentsIndexRouteImport.update({
  id: '/admin/appointments/',
  path: '/admin/appointments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/admin/blog/$id',
  path: '/admin/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/team': typeof TeamRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/appointments/': typeof AdminAppointmentsIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/careers/': typeof AdminCareersIndexRoute
  '/admin/doctors/': typeof AdminDoctorsIndexRoute
  '/admin/faqs/': typeof AdminFaqsIndexRoute
  '/admin/gallery/': typeof AdminGalleryIndexRoute
  '/admin/homepage/': typeof AdminHomepageIndexRoute
  '/admin/popup/': typeof AdminPopupIndexRoute
  '/admin/services/': typeof AdminServicesIndexRoute
  '/admin/testimonials/': typeof AdminTestimonialsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/team': typeof TeamRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/appointments': typeof AdminAppointmentsIndexRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/careers': typeof AdminCareersIndexRoute
  '/admin/doctors': typeof AdminDoctorsIndexRoute
  '/admin/faqs': typeof AdminFaqsIndexRoute
  '/admin/gallery': typeof AdminGalleryIndexRoute
  '/admin/homepage': typeof AdminHomepageIndexRoute
  '/admin/popup': typeof AdminPopupIndexRoute
  '/admin/services': typeof AdminServicesIndexRoute
  '/admin/testimonials': typeof AdminTestimonialsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/team': typeof TeamRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/appointments/': typeof AdminAppointmentsIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/careers/': typeof AdminCareersIndexRoute
  '/admin/doctors/': typeof AdminDoctorsIndexRoute
  '/admin/faqs/': typeof AdminFaqsIndexRoute
  '/admin/gallery/': typeof AdminGalleryIndexRoute
  '/admin/homepage/': typeof AdminHomepageIndexRoute
  '/admin/popup/': typeof AdminPopupIndexRoute
  '/admin/services/': typeof AdminServicesIndexRoute
  '/admin/testimonials/': typeof AdminTestimonialsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/faqs'
    | '/gallery'
    | '/services'
    | '/sitemap.xml'
    | '/success-stories'
    | '/team'
    | '/admin/login'
    | '/blog/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/blog/$id'
    | '/admin/appointments/'
    | '/admin/blog/'
    | '/admin/careers/'
    | '/admin/doctors/'
    | '/admin/faqs/'
    | '/admin/gallery/'
    | '/admin/homepage/'
    | '/admin/popup/'
    | '/admin/services/'
    | '/admin/testimonials/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/faqs'
    | '/gallery'
    | '/services'
    | '/sitemap.xml'
    | '/success-stories'
    | '/team'
    | '/admin/login'
    | '/blog/$slug'
    | '/admin'
    | '/blog'
    | '/admin/blog/$id'
    | '/admin/appointments'
    | '/admin/blog'
    | '/admin/careers'
    | '/admin/doctors'
    | '/admin/faqs'
    | '/admin/gallery'
    | '/admin/homepage'
    | '/admin/popup'
    | '/admin/services'
    | '/admin/testimonials'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/faqs'
    | '/gallery'
    | '/services'
    | '/sitemap.xml'
    | '/success-stories'
    | '/team'
    | '/admin/login'
    | '/blog/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/blog/$id'
    | '/admin/appointments/'
    | '/admin/blog/'
    | '/admin/careers/'
    | '/admin/doctors/'
    | '/admin/faqs/'
    | '/admin/gallery/'
    | '/admin/homepage/'
    | '/admin/popup/'
    | '/admin/services/'
    | '/admin/testimonials/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  GalleryRoute: typeof GalleryRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  TeamRoute: typeof TeamRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BlogSlugRoute: typeof BlogSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminAppointmentsIndexRoute: typeof AdminAppointmentsIndexRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminCareersIndexRoute: typeof AdminCareersIndexRoute
  AdminDoctorsIndexRoute: typeof AdminDoctorsIndexRoute
  AdminFaqsIndexRoute: typeof AdminFaqsIndexRoute
  AdminGalleryIndexRoute: typeof AdminGalleryIndexRoute
  AdminHomepageIndexRoute: typeof AdminHomepageIndexRoute
  AdminPopupIndexRoute: typeof AdminPopupIndexRoute
  AdminServicesIndexRoute: typeof AdminServicesIndexRoute
  AdminTestimonialsIndexRoute: typeof AdminTestimonialsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonials/': {
      id: '/admin/testimonials/'
      path: '/admin/testimonials'
      fullPath: '/admin/testimonials/'
      preLoaderRoute: typeof AdminTestimonialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services/': {
      id: '/admin/services/'
      path: '/admin/services'
      fullPath: '/admin/services/'
      preLoaderRoute: typeof AdminServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/popup/': {
      id: '/admin/popup/'
      path: '/admin/popup'
      fullPath: '/admin/popup/'
      preLoaderRoute: typeof AdminPopupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/homepage/': {
      id: '/admin/homepage/'
      path: '/admin/homepage'
      fullPath: '/admin/homepage/'
      preLoaderRoute: typeof AdminHomepageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gallery/': {
      id: '/admin/gallery/'
      path: '/admin/gallery'
      fullPath: '/admin/gallery/'
      preLoaderRoute: typeof AdminGalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/faqs/': {
      id: '/admin/faqs/'
      path: '/admin/faqs'
      fullPath: '/admin/faqs/'
      preLoaderRoute: typeof AdminFaqsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/doctors/': {
      id: '/admin/doctors/'
      path: '/admin/doctors'
      fullPath: '/admin/doctors/'
      preLoaderRoute: typeof AdminDoctorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/careers/': {
      id: '/admin/careers/'
      path: '/admin/careers'
      fullPath: '/admin/careers/'
      preLoaderRoute: typeof AdminCareersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/admin/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/appointments/': {
      id: '/admin/appointments/'
      path: '/admin/appointments'
      fullPath: '/admin/appointments/'
      preLoaderRoute: typeof AdminAppointmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/admin/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  GalleryRoute: GalleryRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  TeamRoute: TeamRoute,
  AdminLoginRoute: AdminLoginRoute,
  BlogSlugRoute: BlogSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminAppointmentsIndexRoute: AdminAppointmentsIndexRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminCareersIndexRoute: AdminCareersIndexRoute,
  AdminDoctorsIndexRoute: AdminDoctorsIndexRoute,
  AdminFaqsIndexRoute: AdminFaqsIndexRoute,
  AdminGalleryIndexRoute: AdminGalleryIndexRoute,
  AdminHomepageIndexRoute: AdminHomepageIndexRoute,
  AdminPopupIndexRoute: AdminPopupIndexRoute,
  AdminServicesIndexRoute: AdminServicesIndexRoute,
  AdminTestimonialsIndexRoute: AdminTestimonialsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
